### ISSUE TITLE
not compile with samtools 1.2

### ISSUE THREAD

**Issue by boboppie** [genome/pindel#10]
Dear dev,

While runing the install script:
```
$ samtools_HOME=/scratch/modules/samtools/1.2/bin/
$ ./INSTALL ${samtools_HOME}/bin
```
I got an error:
```
pindel.h:34:19: error: khash.h: No such file or directory
```

It worked fine with samtools 0.1.19.

Best wishes,
Fengyuan

**Comment by liangkaiye** [comment]
Indeed, this is the case. The bam handling functions have been changed in the recent samtools versions.
