### ISSUE TITLE
samtools requirements

### ISSUE THREAD

**Issue by snewhouse** [genome/pindel#11]
please include required samtools libs etc in your repo, so users can git clone and just make. 
Makes life nice and easy.

**Comment by EWLameijer** [comment]
Possibly, but one should be very clear towards users, and include that one also makes the samtools (and ensures it doesn't override samtools 1.20, which the user will want to use for 'normal' purposes!) The nasty thing in the matter is that it's not just that Pindel depends on samtools, it's that samtools (or at least the 1.19 version and such) also depend on curses and zlib. If we include samtools in Pindel, there are still some dependencies that may give users headaches, and besides: one should beware of overwriting the Samtools1.20 path.

Also, one should be very clear towards users; I'm not sure if git is installed by standard on the systems of most users; and if it is, if the users (especially if they are 'normal' biologists) have ever used git.

I think the best way to go here is to experiment with setting up Pindel anew in a samtools 1.20 environment, and extend the FAQ (and update the faq http in the INSTALL script).

Longer-term, we want to make Pindel 1.20 compatible, but that will likely take more time and effort. But that would be the sustainable way forward.

We may also consider trying to get rid of the 'normal' samtools dependencies and just replace samtools functionality by our own code or a 'stripped' version of Samtools with fewer dependencies, but that may be very tricky.

Anyway, my proposed course of action would be:

1) uninstall Pindel, reinstall Pindel on a new samtools system and update the Faq so that users can still install pindel
2) update the FAQ address in the INSTALL script
3) add "make Pindel Samtools1.2 compatible" to our list of bugs to fix/features to add.





Date: Mon, 4 May 2015 22:43:07 -0700

**Comment by snewhouse** [comment]
Hi
sure...an update to the FAQ with a link to the exact version of samtools and other dependencies would be the quickest fix & much appreciated. We have NGSeasy users wanting a Dokerised version of Pindel and I keep hitting errors.
Cheers

See below...

I attempted to build in a Docker container with samtools instaledl:-

```
Program: samtools (Tools for alignments in the SAM format)
Version: 1.2-41-g43ca26c (using htslib 1.2.1-69-gb79f40a)
```
Inside my Dockerfile...
```
RUN cd /usr/local/pipeline/ && \
	git clone git://github.com/genome/pindel.git && \
	cd pindel && \
	./INSTALL /usr/local/pipeline/samtools/
```
add this is the error...
```bash
root@e2cc7a92adc1:/usr/local/pipeline/pindel# ./INSTALL /usr/local/pipeline/samtools/
path is now: /usr/local/pipeline/samtools/
WARNING: Created default Makefile.local; please review it.
make: *** No rule to make target 'Makefile.local', needed by 'pindel'.  Stop.
If this is the first time you're running this install script please wait a moment as we create the Makefile.local
make -C src pindel
make[1]: Entering directory '/usr/local/pipeline/pindel/src'
In file included from control_state.h:29:0,
                 from genotyping.h:21,
                 from genotyping.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from assembly.h:21,
                 from assembly.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI.cpp:15:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI_util.h:26:0,
                 from search_MEI_util.cpp:21:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from fn_parameters.cpp:10:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from user_defined_settings.cpp:9:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from pindel_read_reader.h:13:0,
                 from pindel_read_reader.cpp:9:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from ifstream_line_reader.cpp:3:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from read_buffer.h:13:0,
                 from read_buffer.cpp:8:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bddata.h:14,
                 from bddata.cpp:3:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchdeletions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchshortinsertions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from search_variant.cpp:29:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from farend_searcher.cpp:23:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from output_sorter.cpp:27:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bam2depth.h:18,
                 from bam2depth.cpp:12:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_deletions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from control_state.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from refreader.cpp:26:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from searcher.cpp:22:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.cpp:32:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
reader.cpp:31:21: fatal error: kstring.h: No such file or directory
 #include "kstring.h"
                     ^
compilation terminated.
In file included from pindel.cpp:35:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from genotyping.h:21,
                 from genotyping.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from assembly.h:21,
                 from assembly.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI.cpp:15:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI_util.h:26:0,
                 from search_MEI_util.cpp:21:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from fn_parameters.cpp:10:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from user_defined_settings.cpp:9:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from pindel_read_reader.h:13:0,
                 from pindel_read_reader.cpp:9:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from ifstream_line_reader.cpp:3:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from read_buffer.h:13:0,
                 from read_buffer.cpp:8:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bddata.h:14,
                 from bddata.cpp:3:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchdeletions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchshortinsertions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from search_variant.cpp:29:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from farend_searcher.cpp:23:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from output_sorter.cpp:27:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bam2depth.h:18,
                 from bam2depth.cpp:12:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_deletions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from control_state.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from refreader.cpp:26:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from searcher.cpp:22:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.cpp:32:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
reader.cpp:31:21: fatal error: kstring.h: No such file or directory
 #include "kstring.h"
                     ^
compilation terminated.
In file included from pindel.cpp:35:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from genotyping.h:21,
                 from genotyping.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from assembly.h:21,
                 from assembly.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI.cpp:15:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI_util.h:26:0,
                 from search_MEI_util.cpp:21:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from fn_parameters.cpp:10:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from user_defined_settings.cpp:9:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from pindel_read_reader.h:13:0,
                 from pindel_read_reader.cpp:9:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from ifstream_line_reader.cpp:3:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from read_buffer.h:13:0,
                 from read_buffer.cpp:8:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bddata.h:14,
                 from bddata.cpp:3:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchdeletions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchshortinsertions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from search_variant.cpp:29:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from farend_searcher.cpp:23:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from output_sorter.cpp:27:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bam2depth.h:18,
                 from bam2depth.cpp:12:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_deletions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from control_state.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from refreader.cpp:26:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from searcher.cpp:22:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.cpp:32:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
reader.cpp:31:21: fatal error: kstring.h: No such file or directory
 #include "kstring.h"
                     ^
compilation terminated.
In file included from pindel.cpp:35:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from genotyping.h:21,
                 from genotyping.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from assembly.h:21,
                 from assembly.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI.cpp:15:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from search_MEI_util.h:26:0,
                 from search_MEI_util.cpp:21:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from fn_parameters.cpp:10:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from user_defined_settings.cpp:9:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from pindel_read_reader.h:13:0,
                 from pindel_read_reader.cpp:9:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from ifstream_line_reader.cpp:3:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from read_buffer.h:13:0,
                 from read_buffer.cpp:8:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bddata.h:14,
                 from bddata.cpp:3:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchdeletions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from searchshortinsertions.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from search_variant.cpp:29:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from farend_searcher.cpp:23:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from output_sorter.cpp:27:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_tandem_duplications.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from bam2depth.h:18,
                 from bam2depth.cpp:12:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_inversions.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.h:27:0,
                 from search_deletions_nt.cpp:23:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from control_state.h:29:0,
                 from control_state.cpp:22:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from refreader.cpp:26:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from searcher.cpp:22:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
In file included from reporter.cpp:32:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
reader.cpp:31:21: fatal error: kstring.h: No such file or directory
 #include "kstring.h"
                     ^
compilation terminated.
In file included from pindel.cpp:35:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
g++  -Wall -g -c -O3 -fopenmp -I/usr/local/pipeline/samtools/ pindel.cpp -o pindel.o
In file included from pindel.cpp:35:0:
pindel.h:34:19: fatal error: khash.h: No such file or directory
 #include "khash.h"
                   ^
compilation terminated.
Makefile:47: recipe for target 'pindel.o' failed
make[1]: *** [pindel.o] Error 1
make[1]: Leaving directory '/usr/local/pipeline/pindel/src'
Makefile:12: recipe for target 'pindel' failed
make: *** [pindel] Error 2

INSTALL failed
Possible reasons:
1. 'cannot cd to [path]
->the samtools path provided was incorrect
(so '../samtools/' was used instead of '/home/user/samtools/')

2. 'cannot find -lbam'
->samtools was not properly installed, in that case go to the samtools directory
and run 'make'.

For futher help, see the pindel wiki and
```

**Comment by snewhouse** [comment]
compiles with samtools-0.1.19

**Dockerfile snippet**
```
ADD samtools-0.1.19.tar.bz2 /usr/local/pipeline/

RUN cd /usr/local/pipeline/ && \
	cd samtools-0.1.19 && \
	make

RUN cd /usr/local/pipeline/ && \
	git clone git://github.com/genome/pindel.git && \
	cd pindel && \
	/bin/sh ./INSTALL /usr/local/pipeline/samtools-0.1.19
```

**Comment by jmarshall** [comment]
> Longer-term, we want to make Pindel 1.20 compatible, but that will likely take more time and effort. But that would be the sustainable way forward.

The samtools/htslib maintainers would certainly recommend changing Pindel to use the maintained HTSlib API rather than its current old-samtools legacy API.  This would be a much better approach than bundling an old unmaintained version of samtools and its bugs within Pindel.  It would also enable Pindel to work with CRAM files as well as BAM files.

See PR #12 which does most of this, though I am not equipped to test it extensively.

**Comment by dakl** [comment]
Has this transition been completed?

**Comment by liangkaiye** [comment]
Yes. Now compiled on htslib.

**Comment by ckr123tw** [comment]
I still encountered the same problem.

Tried to compile samtools under different settings, and I have sam.h under several locations:
/usr/local/Apps/samtools-1.3/htslib-1.3/htslib/sam.h
/usr/local/Apps/samtools-1.3/htslib-1.3/include/htslib/sam.h
/usr/local/Apps/samtools-1.3/sam.h
/usr/local/Apps/samtools-1.3/include/htslib/sam.h

But none of the following compilation worked.

./INSTALL /usr/local/Apps/samtools-1.3
_path is now: /usr/local/Apps/samtools-1.3/
make -C src pindel
make[1]: Entering directory `/usr/local/Apps/pindel/src'
g++  -I/usr/local/bin -Wall -g -c -O3 -fopenmp pindel.cpp -o pindel.o
make[1]: Leaving directory `/usr/local/Apps/pindel/src'
error: htslib/khash.h: No such file or directory
error: htslib/sam.h: No such file or directory_


./INSTALL /usr/local/Apps/samtools-1.3/htslib-1.3/
_path is now: /usr/local/Apps/samtools-1.3/htslib-1.3/
make -C src pindel
make[1]: Entering directory `/usr/local/Apps/pindel/src'
g++  -I/usr/local/bin -Wall -g -c -O3 -fopenmp pindel.cpp -o pindel.o
make[1]: Leaving directory `/usr/local/Apps/pindel/src'_

Both compilation returned error messages:
error: htslib/khash.h: No such file or directory
error: htslib/sam.h: No such file or directory

Any suggestions?

**Comment by liangkaiye** [comment]
./INSTALL /usr/local/Apps/samtools-1.2/htslib-1.2/

we have not tested newer version of samtools.

**Comment by EWLameijer** [comment]
Ehmm... what Kai said, but as I am a bit more verbose: the newer versions of Pindel use htslib, not samtools. 

For the rest it may help if you can provide us with a little more data.

For example, are you trying to install under OS X, or Linux?

About OS X: there is a discussion somewhere else on the internet

https://www.biostars.org/p/145603/ 

This may be of some help.

We also added a FAQ! - compiling pindel on OS X can be a bit tricky...

For the rest, my recommendation would be to try clone samtools/htslib as well as Pindel freshly from git, get htslib (and possibly samtools) installed properly, and then try the Pindel install again...

Anyway, if that also doesn't work, please let us know the exact steps you did, I can try to make some time to reproduce your problem.

**Comment by ckr123tw** [comment]
Thanks for the suggestions. I am trying to install under Linux.

Tried the following:

Under samtools-1.2
_make
make prefix=/usr/local/Apps/samtools-1.2 install_

Under samtools-1.2/htslib-1.2.1
_./configure prefix=/usr/local/Apps/samtools-1.2/htslib-1.2.1/
make
make install_

Checked to make sure that sam.h is under both
/usr/local/Apps/samtools-1.2/htslib-1.2.1/include/htslib
/usr/local/Apps/samtools-1.2/htslib-1.2.1/htslib

Under pindel folder
_./INSTALL /usr/local/Apps/samtools-1.2/htslib-1.2.1/
./INSTALL /usr/local/Apps/samtools-1.2/htslib-1.2.1/include
./INSTALL /usr/local/Apps/samtools-1.2/htslib-1.2.1/include/htslib
./INSTALL /usr/local/Apps/samtools-1.2/_

error: htslib/khash.h: No such file or directory
error: htslib/sam.h: No such file or directory

**Comment by EWLameijer** [comment]
Hmm.. just to let you know that I'm looking at it; I actually could reproduce the khash errors while building brazenly with Eclipse. However, it was not (as I first thought) because of the directory structure. On my computer, ./INSTALL [path]/htslib-1.2.1 just works, but note that my path was ../Desktop/Pindel_Related/htslib-1.2.1 , so I do not have samtools in my path at all!

My current (working) attempt, could you perhaps try to reproduce it?
1) create a directory (for example "mkdir pindeltest", then "cd pindeltest")
2) clone pindel into it ("git clone https://github.com/genome/pindel")
3) clone htslib into it ("git clone https://github.com/samtools/htslib")
4) go to the htslib directory and prepare everything properly ("cd htslib", "make", "sudo make install")
5) go to the pindel directory and install ("cd ../pindel", "./INSTALL ../htslib")
6) if all things go well, you can now run pindel (say "./pindel")

Could you try this out and tell us whether this works for you, or whether something goes wrong?

Best regards,

Eric-Wubbo

**Comment by ckr123tw** [comment]
Hi Eric,

Thank you for making time to reproduce the problem.

I followed your instructions, and did something differently:
_4) go to the htslib directory and prepare everything properly ("cd htslib", "make", "sudo make install")_
The cloned htslib does not have ./configure, so I edited the Makefile and replaced the prefix with /usr/local/Apps/pindeltest/htslib

Everything works great now. Really appreciate it.

Best,

**Comment by EWLameijer** [comment]
Hi Ckr,

thank you for your comment; I'm glad it worked (even though I'm still unsure why it didn't work in the first place), but in any case I'm grateful for your original question; quite some people may needlessly give up on pindel due to such khash errors but may not always have time, energy or motivation to ask us questions. This way I can put it in the FAQ or in another easily accessible repository, so future users can solve problems like these faster and more easily than we did.

Best regards,

Eric-Wubbo

**Comment by EWLameijer** [comment]
Hi Ckr,

I've updated the FAQ. Thank you again for your help!

@snewhouse: what to do with users having problems with htslib is in my opinion something that should be decided by the lead architect and developer of Pindel, namely Kai. Personally I don't think that we should try to include htslib in the pindel repository (that would mean that every time htslib is improved, we should update the pindel branch as well!), but possibly we (or you!) can make a script that clones and installs htslib if the user has problems installing pindel.

As this issue is however almost 1 year old, I will take the liberty of closing it. If in future this remains a problem, I hope that someone will reopen it.

Best regards,

Eric-Wubbo
